services:
  - type: web
    name: seismosense
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: KAFKA_BOOTSTRAP_SERVERS
        sync: false
      - key: KAFKA_SSL_CAFILE
        value: /etc/secrets/ca.pem
      - key: KAFKA_SSL_CERTFILE
        value: /etc/secrets/service.cert
      - key: KAFKA_SSL_KEYFILE
        value: /etc/secrets/service.key
      - key: SECRET_KEY
        generateValue: true
